// Code generated by go-swagger; DO NOT EDIT.

// Package restapi CloudTides-Server
//
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /api/v1
//  Version: 0.0.1
//
//  Consumes:
//    - application/json
//    - multipart/form-data
//
//  Produces:
//    - application/octet-stream
//    - application/json
//
// swagger:meta
package restapi
