// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// AchieveHostOKCode is the HTTP code returned for type AchieveHostOK
const AchieveHostOKCode int = 200

/*AchieveHostOK OK

swagger:response achieveHostOK
*/
type AchieveHostOK struct {

	/*
	  In: Body
	*/
	Payload []*AchieveHostOKBodyItems0 `json:"body,omitempty"`
}

// NewAchieveHostOK creates AchieveHostOK with default headers values
func NewAchieveHostOK() *AchieveHostOK {

	return &AchieveHostOK{}
}

// WithPayload adds the payload to the achieve host o k response
func (o *AchieveHostOK) WithPayload(payload []*AchieveHostOKBodyItems0) *AchieveHostOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the achieve host o k response
func (o *AchieveHostOK) SetPayload(payload []*AchieveHostOKBodyItems0) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AchieveHostOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*AchieveHostOKBodyItems0, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// AchieveHostUnauthorizedCode is the HTTP code returned for type AchieveHostUnauthorized
const AchieveHostUnauthorizedCode int = 401

/*AchieveHostUnauthorized Unauthorized

swagger:response achieveHostUnauthorized
*/
type AchieveHostUnauthorized struct {
}

// NewAchieveHostUnauthorized creates AchieveHostUnauthorized with default headers values
func NewAchieveHostUnauthorized() *AchieveHostUnauthorized {

	return &AchieveHostUnauthorized{}
}

// WriteResponse to the client
func (o *AchieveHostUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// AchieveHostForbiddenCode is the HTTP code returned for type AchieveHostForbidden
const AchieveHostForbiddenCode int = 403

/*AchieveHostForbidden Forbidden

swagger:response achieveHostForbidden
*/
type AchieveHostForbidden struct {
}

// NewAchieveHostForbidden creates AchieveHostForbidden with default headers values
func NewAchieveHostForbidden() *AchieveHostForbidden {

	return &AchieveHostForbidden{}
}

// WriteResponse to the client
func (o *AchieveHostForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
