// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DeleteApplicationInstanceHandlerFunc turns a function with the right signature into a delete application instance handler
type DeleteApplicationInstanceHandlerFunc func(DeleteApplicationInstanceParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteApplicationInstanceHandlerFunc) Handle(params DeleteApplicationInstanceParams) middleware.Responder {
	return fn(params)
}

// DeleteApplicationInstanceHandler interface for that can handle valid delete application instance params
type DeleteApplicationInstanceHandler interface {
	Handle(DeleteApplicationInstanceParams) middleware.Responder
}

// NewDeleteApplicationInstance creates a new http.Handler for the delete application instance operation
func NewDeleteApplicationInstance(ctx *middleware.Context, handler DeleteApplicationInstanceHandler) *DeleteApplicationInstance {
	return &DeleteApplicationInstance{Context: ctx, Handler: handler}
}

/* DeleteApplicationInstance swagger:route DELETE /application/instance/{token} application deleteApplicationInstance

delete application instance

*/
type DeleteApplicationInstance struct {
	Context *middleware.Context
	Handler DeleteApplicationInstanceHandler
}

func (o *DeleteApplicationInstance) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteApplicationInstanceParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// DeleteApplicationInstanceOKBody delete application instance o k body
//
// swagger:model DeleteApplicationInstanceOKBody
type DeleteApplicationInstanceOKBody struct {

	// msg
	Msg string `json:"msg,omitempty"`
}

// Validate validates this delete application instance o k body
func (o *DeleteApplicationInstanceOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this delete application instance o k body based on context it is used
func (o *DeleteApplicationInstanceOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DeleteApplicationInstanceOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteApplicationInstanceOKBody) UnmarshalBinary(b []byte) error {
	var res DeleteApplicationInstanceOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
