// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteApplicationInstanceOKCode is the HTTP code returned for type DeleteApplicationInstanceOK
const DeleteApplicationInstanceOKCode int = 200

/*DeleteApplicationInstanceOK OK

swagger:response deleteApplicationInstanceOK
*/
type DeleteApplicationInstanceOK struct {

	/*
	  In: Body
	*/
	Payload *DeleteApplicationInstanceOKBody `json:"body,omitempty"`
}

// NewDeleteApplicationInstanceOK creates DeleteApplicationInstanceOK with default headers values
func NewDeleteApplicationInstanceOK() *DeleteApplicationInstanceOK {

	return &DeleteApplicationInstanceOK{}
}

// WithPayload adds the payload to the delete application instance o k response
func (o *DeleteApplicationInstanceOK) WithPayload(payload *DeleteApplicationInstanceOKBody) *DeleteApplicationInstanceOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete application instance o k response
func (o *DeleteApplicationInstanceOK) SetPayload(payload *DeleteApplicationInstanceOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteApplicationInstanceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteApplicationInstanceUnauthorizedCode is the HTTP code returned for type DeleteApplicationInstanceUnauthorized
const DeleteApplicationInstanceUnauthorizedCode int = 401

/*DeleteApplicationInstanceUnauthorized Unauthorized

swagger:response deleteApplicationInstanceUnauthorized
*/
type DeleteApplicationInstanceUnauthorized struct {
}

// NewDeleteApplicationInstanceUnauthorized creates DeleteApplicationInstanceUnauthorized with default headers values
func NewDeleteApplicationInstanceUnauthorized() *DeleteApplicationInstanceUnauthorized {

	return &DeleteApplicationInstanceUnauthorized{}
}

// WriteResponse to the client
func (o *DeleteApplicationInstanceUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// DeleteApplicationInstanceForbiddenCode is the HTTP code returned for type DeleteApplicationInstanceForbidden
const DeleteApplicationInstanceForbiddenCode int = 403

/*DeleteApplicationInstanceForbidden Forbidden

swagger:response deleteApplicationInstanceForbidden
*/
type DeleteApplicationInstanceForbidden struct {
}

// NewDeleteApplicationInstanceForbidden creates DeleteApplicationInstanceForbidden with default headers values
func NewDeleteApplicationInstanceForbidden() *DeleteApplicationInstanceForbidden {

	return &DeleteApplicationInstanceForbidden{}
}

// WriteResponse to the client
func (o *DeleteApplicationInstanceForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
