// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DownInstanceFileHandlerFunc turns a function with the right signature into a down instance file handler
type DownInstanceFileHandlerFunc func(DownInstanceFileParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DownInstanceFileHandlerFunc) Handle(params DownInstanceFileParams) middleware.Responder {
	return fn(params)
}

// DownInstanceFileHandler interface for that can handle valid down instance file params
type DownInstanceFileHandler interface {
	Handle(DownInstanceFileParams) middleware.Responder
}

// NewDownInstanceFile creates a new http.Handler for the down instance file operation
func NewDownInstanceFile(ctx *middleware.Context, handler DownInstanceFileHandler) *DownInstanceFile {
	return &DownInstanceFile{Context: ctx, Handler: handler}
}

/* DownInstanceFile swagger:route GET /application/instance/file/{uid}/{token}/{name} application downInstanceFile

down files to instances

*/
type DownInstanceFile struct {
	Context *middleware.Context
	Handler DownInstanceFileHandler
}

func (o *DownInstanceFile) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDownInstanceFileParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
