// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DownInstanceFileOKCode is the HTTP code returned for type DownInstanceFileOK
const DownInstanceFileOKCode int = 200

/*DownInstanceFileOK OK

swagger:response downInstanceFileOK
*/
type DownInstanceFileOK struct {
}

// NewDownInstanceFileOK creates DownInstanceFileOK with default headers values
func NewDownInstanceFileOK() *DownInstanceFileOK {

	return &DownInstanceFileOK{}
}

// WriteResponse to the client
func (o *DownInstanceFileOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
