// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetApplicationInstanceLogsOKCode is the HTTP code returned for type GetApplicationInstanceLogsOK
const GetApplicationInstanceLogsOKCode int = 200

/*GetApplicationInstanceLogsOK OK

swagger:response getApplicationInstanceLogsOK
*/
type GetApplicationInstanceLogsOK struct {

	/*
	  In: Body
	*/
	Payload []*GetApplicationInstanceLogsOKBodyItems0 `json:"body,omitempty"`
}

// NewGetApplicationInstanceLogsOK creates GetApplicationInstanceLogsOK with default headers values
func NewGetApplicationInstanceLogsOK() *GetApplicationInstanceLogsOK {

	return &GetApplicationInstanceLogsOK{}
}

// WithPayload adds the payload to the get application instance logs o k response
func (o *GetApplicationInstanceLogsOK) WithPayload(payload []*GetApplicationInstanceLogsOKBodyItems0) *GetApplicationInstanceLogsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get application instance logs o k response
func (o *GetApplicationInstanceLogsOK) SetPayload(payload []*GetApplicationInstanceLogsOKBodyItems0) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetApplicationInstanceLogsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*GetApplicationInstanceLogsOKBodyItems0, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetApplicationInstanceLogsUnauthorizedCode is the HTTP code returned for type GetApplicationInstanceLogsUnauthorized
const GetApplicationInstanceLogsUnauthorizedCode int = 401

/*GetApplicationInstanceLogsUnauthorized Unauthorized

swagger:response getApplicationInstanceLogsUnauthorized
*/
type GetApplicationInstanceLogsUnauthorized struct {
}

// NewGetApplicationInstanceLogsUnauthorized creates GetApplicationInstanceLogsUnauthorized with default headers values
func NewGetApplicationInstanceLogsUnauthorized() *GetApplicationInstanceLogsUnauthorized {

	return &GetApplicationInstanceLogsUnauthorized{}
}

// WriteResponse to the client
func (o *GetApplicationInstanceLogsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// GetApplicationInstanceLogsForbiddenCode is the HTTP code returned for type GetApplicationInstanceLogsForbidden
const GetApplicationInstanceLogsForbiddenCode int = 403

/*GetApplicationInstanceLogsForbidden Forbidden

swagger:response getApplicationInstanceLogsForbidden
*/
type GetApplicationInstanceLogsForbidden struct {
}

// NewGetApplicationInstanceLogsForbidden creates GetApplicationInstanceLogsForbidden with default headers values
func NewGetApplicationInstanceLogsForbidden() *GetApplicationInstanceLogsForbidden {

	return &GetApplicationInstanceLogsForbidden{}
}

// WriteResponse to the client
func (o *GetApplicationInstanceLogsForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
