// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetApplicationInstanceLogsHandlerFunc turns a function with the right signature into a get application instance logs handler
type GetApplicationInstanceLogsHandlerFunc func(GetApplicationInstanceLogsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetApplicationInstanceLogsHandlerFunc) Handle(params GetApplicationInstanceLogsParams) middleware.Responder {
	return fn(params)
}

// GetApplicationInstanceLogsHandler interface for that can handle valid get application instance logs params
type GetApplicationInstanceLogsHandler interface {
	Handle(GetApplicationInstanceLogsParams) middleware.Responder
}

// NewGetApplicationInstanceLogs creates a new http.Handler for the get application instance logs operation
func NewGetApplicationInstanceLogs(ctx *middleware.Context, handler GetApplicationInstanceLogsHandler) *GetApplicationInstanceLogs {
	return &GetApplicationInstanceLogs{Context: ctx, Handler: handler}
}

/* GetApplicationInstanceLogs swagger:route GET /application/instance/{token} application getApplicationInstanceLogs

get application instance logs

*/
type GetApplicationInstanceLogs struct {
	Context *middleware.Context
	Handler GetApplicationInstanceLogsHandler
}

func (o *GetApplicationInstanceLogs) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetApplicationInstanceLogsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetApplicationInstanceLogsOKBodyItems0 get application instance logs o k body items0
//
// swagger:model GetApplicationInstanceLogsOKBodyItems0
type GetApplicationInstanceLogsOKBodyItems0 struct {

	// content
	Content string `json:"content,omitempty"`

	// data
	Data string `json:"data,omitempty"`

	// leve
	Leve string `json:"leve,omitempty"`

	// source
	Source string `json:"source,omitempty"`

	// time
	Time string `json:"time,omitempty"`
}

// Validate validates this get application instance logs o k body items0
func (o *GetApplicationInstanceLogsOKBodyItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get application instance logs o k body items0 based on context it is used
func (o *GetApplicationInstanceLogsOKBodyItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetApplicationInstanceLogsOKBodyItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetApplicationInstanceLogsOKBodyItems0) UnmarshalBinary(b []byte) error {
	var res GetApplicationInstanceLogsOKBodyItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
