// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// ListApplicationInstanceOKCode is the HTTP code returned for type ListApplicationInstanceOK
const ListApplicationInstanceOKCode int = 200

/*ListApplicationInstanceOK OK

swagger:response listApplicationInstanceOK
*/
type ListApplicationInstanceOK struct {

	/*
	  In: Body
	*/
	Payload []*ListApplicationInstanceOKBodyItems0 `json:"body,omitempty"`
}

// NewListApplicationInstanceOK creates ListApplicationInstanceOK with default headers values
func NewListApplicationInstanceOK() *ListApplicationInstanceOK {

	return &ListApplicationInstanceOK{}
}

// WithPayload adds the payload to the list application instance o k response
func (o *ListApplicationInstanceOK) WithPayload(payload []*ListApplicationInstanceOKBodyItems0) *ListApplicationInstanceOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list application instance o k response
func (o *ListApplicationInstanceOK) SetPayload(payload []*ListApplicationInstanceOKBodyItems0) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListApplicationInstanceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*ListApplicationInstanceOKBodyItems0, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// ListApplicationInstanceUnauthorizedCode is the HTTP code returned for type ListApplicationInstanceUnauthorized
const ListApplicationInstanceUnauthorizedCode int = 401

/*ListApplicationInstanceUnauthorized Unauthorized

swagger:response listApplicationInstanceUnauthorized
*/
type ListApplicationInstanceUnauthorized struct {
}

// NewListApplicationInstanceUnauthorized creates ListApplicationInstanceUnauthorized with default headers values
func NewListApplicationInstanceUnauthorized() *ListApplicationInstanceUnauthorized {

	return &ListApplicationInstanceUnauthorized{}
}

// WriteResponse to the client
func (o *ListApplicationInstanceUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// ListApplicationInstanceForbiddenCode is the HTTP code returned for type ListApplicationInstanceForbidden
const ListApplicationInstanceForbiddenCode int = 403

/*ListApplicationInstanceForbidden Forbidden

swagger:response listApplicationInstanceForbidden
*/
type ListApplicationInstanceForbidden struct {
}

// NewListApplicationInstanceForbidden creates ListApplicationInstanceForbidden with default headers values
func NewListApplicationInstanceForbidden() *ListApplicationInstanceForbidden {

	return &ListApplicationInstanceForbidden{}
}

// WriteResponse to the client
func (o *ListApplicationInstanceForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
