// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ListInstanceFilesHandlerFunc turns a function with the right signature into a list instance files handler
type ListInstanceFilesHandlerFunc func(ListInstanceFilesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListInstanceFilesHandlerFunc) Handle(params ListInstanceFilesParams) middleware.Responder {
	return fn(params)
}

// ListInstanceFilesHandler interface for that can handle valid list instance files params
type ListInstanceFilesHandler interface {
	Handle(ListInstanceFilesParams) middleware.Responder
}

// NewListInstanceFiles creates a new http.Handler for the list instance files operation
func NewListInstanceFiles(ctx *middleware.Context, handler ListInstanceFilesHandler) *ListInstanceFiles {
	return &ListInstanceFiles{Context: ctx, Handler: handler}
}

/* ListInstanceFiles swagger:route GET /application/instance/file/{token} application listInstanceFiles

list files to instances

*/
type ListInstanceFiles struct {
	Context *middleware.Context
	Handler ListInstanceFilesHandler
}

func (o *ListInstanceFiles) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewListInstanceFilesParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// ListInstanceFilesOKBodyItems0 list instance files o k body items0
//
// swagger:model ListInstanceFilesOKBodyItems0
type ListInstanceFilesOKBodyItems0 struct {

	// createtime
	Createtime string `json:"createtime,omitempty"`

	// downlink
	Downlink string `json:"downlink,omitempty"`

	// filename
	Filename string `json:"filename,omitempty"`

	// filesize
	Filesize string `json:"filesize,omitempty"`
}

// Validate validates this list instance files o k body items0
func (o *ListInstanceFilesOKBodyItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this list instance files o k body items0 based on context it is used
func (o *ListInstanceFilesOKBodyItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *ListInstanceFilesOKBodyItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ListInstanceFilesOKBodyItems0) UnmarshalBinary(b []byte) error {
	var res ListInstanceFilesOKBodyItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
