// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SearchInstanceHandlerFunc turns a function with the right signature into a search instance handler
type SearchInstanceHandlerFunc func(SearchInstanceParams) middleware.Responder

// Handle executing the request and returning a response
func (fn SearchInstanceHandlerFunc) Handle(params SearchInstanceParams) middleware.Responder {
	return fn(params)
}

// SearchInstanceHandler interface for that can handle valid search instance params
type SearchInstanceHandler interface {
	Handle(SearchInstanceParams) middleware.Responder
}

// NewSearchInstance creates a new http.Handler for the search instance operation
func NewSearchInstance(ctx *middleware.Context, handler SearchInstanceHandler) *SearchInstance {
	return &SearchInstance{Context: ctx, Handler: handler}
}

/* SearchInstance swagger:route GET /application/instance/details/{token} application searchInstance

search instance

*/
type SearchInstance struct {
	Context *middleware.Context
	Handler SearchInstanceHandler
}

func (o *SearchInstance) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewSearchInstanceParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// SearchInstanceOKBody search instance o k body
//
// swagger:model SearchInstanceOKBody
type SearchInstanceOKBody struct {

	// data
	Data string `json:"data,omitempty"`
}

// Validate validates this search instance o k body
func (o *SearchInstanceOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this search instance o k body based on context it is used
func (o *SearchInstanceOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *SearchInstanceOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *SearchInstanceOKBody) UnmarshalBinary(b []byte) error {
	var res SearchInstanceOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
