// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// SearchInstanceOKCode is the HTTP code returned for type SearchInstanceOK
const SearchInstanceOKCode int = 200

/*SearchInstanceOK OK

swagger:response searchInstanceOK
*/
type SearchInstanceOK struct {

	/*
	  In: Body
	*/
	Payload *SearchInstanceOKBody `json:"body,omitempty"`
}

// NewSearchInstanceOK creates SearchInstanceOK with default headers values
func NewSearchInstanceOK() *SearchInstanceOK {

	return &SearchInstanceOK{}
}

// WithPayload adds the payload to the search instance o k response
func (o *SearchInstanceOK) WithPayload(payload *SearchInstanceOKBody) *SearchInstanceOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the search instance o k response
func (o *SearchInstanceOK) SetPayload(payload *SearchInstanceOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SearchInstanceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
