// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// WatchApplicationInstanceLogsHandlerFunc turns a function with the right signature into a watch application instance logs handler
type WatchApplicationInstanceLogsHandlerFunc func(WatchApplicationInstanceLogsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn WatchApplicationInstanceLogsHandlerFunc) Handle(params WatchApplicationInstanceLogsParams) middleware.Responder {
	return fn(params)
}

// WatchApplicationInstanceLogsHandler interface for that can handle valid watch application instance logs params
type WatchApplicationInstanceLogsHandler interface {
	Handle(WatchApplicationInstanceLogsParams) middleware.Responder
}

// NewWatchApplicationInstanceLogs creates a new http.Handler for the watch application instance logs operation
func NewWatchApplicationInstanceLogs(ctx *middleware.Context, handler WatchApplicationInstanceLogsHandler) *WatchApplicationInstanceLogs {
	return &WatchApplicationInstanceLogs{Context: ctx, Handler: handler}
}

/* WatchApplicationInstanceLogs swagger:route GET /application/instance/{token} application watchApplicationInstanceLogs

watch application instance logs

*/
type WatchApplicationInstanceLogs struct {
	Context *middleware.Context
	Handler WatchApplicationInstanceLogsHandler
}

func (o *WatchApplicationInstanceLogs) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewWatchApplicationInstanceLogsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// WatchApplicationInstanceLogsOKBodyItems0 watch application instance logs o k body items0
//
// swagger:model WatchApplicationInstanceLogsOKBodyItems0
type WatchApplicationInstanceLogsOKBodyItems0 struct {

	// content
	Content string `json:"content,omitempty"`

	// date
	Date string `json:"date,omitempty"`

	// leve
	Leve string `json:"leve,omitempty"`

	// source
	Source string `json:"source,omitempty"`

	// time
	Time string `json:"time,omitempty"`
}

// Validate validates this watch application instance logs o k body items0
func (o *WatchApplicationInstanceLogsOKBodyItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this watch application instance logs o k body items0 based on context it is used
func (o *WatchApplicationInstanceLogsOKBodyItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *WatchApplicationInstanceLogsOKBodyItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *WatchApplicationInstanceLogsOKBodyItems0) UnmarshalBinary(b []byte) error {
	var res WatchApplicationInstanceLogsOKBodyItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
