// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// WatchApplicationInstanceLogsOKCode is the HTTP code returned for type WatchApplicationInstanceLogsOK
const WatchApplicationInstanceLogsOKCode int = 200

/*WatchApplicationInstanceLogsOK OK

swagger:response watchApplicationInstanceLogsOK
*/
type WatchApplicationInstanceLogsOK struct {

	/*
	  In: Body
	*/
	Payload []*WatchApplicationInstanceLogsOKBodyItems0 `json:"body,omitempty"`
}

// NewWatchApplicationInstanceLogsOK creates WatchApplicationInstanceLogsOK with default headers values
func NewWatchApplicationInstanceLogsOK() *WatchApplicationInstanceLogsOK {

	return &WatchApplicationInstanceLogsOK{}
}

// WithPayload adds the payload to the watch application instance logs o k response
func (o *WatchApplicationInstanceLogsOK) WithPayload(payload []*WatchApplicationInstanceLogsOKBodyItems0) *WatchApplicationInstanceLogsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the watch application instance logs o k response
func (o *WatchApplicationInstanceLogsOK) SetPayload(payload []*WatchApplicationInstanceLogsOKBodyItems0) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *WatchApplicationInstanceLogsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*WatchApplicationInstanceLogsOKBodyItems0, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// WatchApplicationInstanceLogsUnauthorizedCode is the HTTP code returned for type WatchApplicationInstanceLogsUnauthorized
const WatchApplicationInstanceLogsUnauthorizedCode int = 401

/*WatchApplicationInstanceLogsUnauthorized Unauthorized

swagger:response watchApplicationInstanceLogsUnauthorized
*/
type WatchApplicationInstanceLogsUnauthorized struct {
}

// NewWatchApplicationInstanceLogsUnauthorized creates WatchApplicationInstanceLogsUnauthorized with default headers values
func NewWatchApplicationInstanceLogsUnauthorized() *WatchApplicationInstanceLogsUnauthorized {

	return &WatchApplicationInstanceLogsUnauthorized{}
}

// WriteResponse to the client
func (o *WatchApplicationInstanceLogsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// WatchApplicationInstanceLogsForbiddenCode is the HTTP code returned for type WatchApplicationInstanceLogsForbidden
const WatchApplicationInstanceLogsForbiddenCode int = 403

/*WatchApplicationInstanceLogsForbidden Forbidden

swagger:response watchApplicationInstanceLogsForbidden
*/
type WatchApplicationInstanceLogsForbidden struct {
}

// NewWatchApplicationInstanceLogsForbidden creates WatchApplicationInstanceLogsForbidden with default headers values
func NewWatchApplicationInstanceLogsForbidden() *WatchApplicationInstanceLogsForbidden {

	return &WatchApplicationInstanceLogsForbidden{}
}

// WriteResponse to the client
func (o *WatchApplicationInstanceLogsForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
